version: '3.9'

services:
  emailweb:
    container_name: emailweb
    #image: emailweb:latest
    image: 127.0.0.1:8083/emailweb:latest

    networks:
      - sma_network

    environment:
      - serviceName=emailweb
      - servicePort=8000
      - projectName=emailweb
      - VITE_SMA_APP_BACKEND_URL=http://10.89.104.58:8000
      - VITE_SMA_APP_KEYCLOAK_URL=http://10.89.104.58:8000
      - VITE_SMA_ENABLE_MAILLINK_PROTECTION=TRUE
    entrypoint: ["pnpm", "run", "serve"]
    restart: always
networks:
  sma_network:
    external: true
    